_format_version: "1.1"

services:
  - name: exemplo_service
    url: https://run.mocky.io/v3/e002349c-8c93-4022-913b-df9cb6960605
    routes:
        - name: Exemplo_route
          methods:
          - GET
          paths:
          - /exemplo$
